### ISSUE TITLE
Possible nullptr with SmsDb::getOne and SmsDb::getLast

### ISSUE THREAD

**Issue by Koci0** [Koci0/Nokia-PK-2021#30]
We do not check for `nulltpr` anywhere, so we should add it or (even better) switch from pointers to references.

**Comment by robertKozik** [comment]
I'm checking out documentation [(here)](https://www.cplusplus.com/reference/vector/vector/at/) about std::vector.at function which is used in SmsDb::getOne and it looks like there will be no nullptr, only `out_of range` exception.

**Comment by Koci0** [comment]
You are right, and as we manually tested all the expected behavior and possible states, we can close this issue as is.
