### ISSUE TITLE
Error handleCallAccepted

### ISSUE THREAD

**Issue by ghost** [Koci0/Nokia-PK-2021#31]
After successful accepting the call request by selecting Accept option, the message pops up in UE terminal:
"[ERROR]: [phone:1][TalkingState]Unexpected: handleCallAccepted".

**Comment by robertKozik** [comment]
I have probably found the reason why it works that way. We are sending CallAccept message when UE change state to Talking State, this way both UEs involved in this connecton sends CallAccept message, while according to documentation only UE receiving call should do this.If I'm mistaken about the documentation part please correct me 😄. I'll propose fix ASAP.
